source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'BeatDemo' do

    # 信息
    pod 'XLActionController'                                    # 底部选择
    pod 'XLActionController/Skype'                              # 底部选择(Skype)
    pod 'SwiftMessages'                                         # 信息提示
    pod 'SVProgressHUD'                                         # 加载中菊花
    pod 'ButtonProgressBar-iOS'                                 # 进度条按钮

    # 界面
    pod 'Hero'                                                  # 转场
    pod 'SnapKit', '~> 4.0.0'                                   # 布局
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git' # 颜色扩展

    # 音频处理
    pod 'AudioKit', '~> 4.0'
    pod 'AudioKit/UI'
    
    # 数据处理
#    pod 'RxSwift',    '~> 4.0'
#    pod 'RxCocoa',    '~> 4.0'

end
